"""add daily activity

Revision ID: 0c891e620ada
Revises: c604d8768ff8
Create Date: 2026-08-06 17:13:08.114831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c891e620ada'
down_revision: Union[str, Sequence[str], None] = 'c604d8768ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_id', name='uq_daily_activity_attendance')
    )
    op.create_index(op.f('ix_daily_activities_id'), 'daily_activities', ['id'], unique=False)
    op.create_table('daily_activity_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_activity_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_activities.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_activity_id', 'task_id', name='uq_activity_task')
    )
    op.create_index(op.f('ix_daily_activity_items_id'), 'daily_activity_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_activity_items_id'), table_name='daily_activity_items')
    op.drop_table('daily_activity_items')
    op.drop_index(op.f('ix_daily_activities_id'), table_name='daily_activities')
    op.drop_table('daily_activities')
    # ### end Alembic commands ###
