"""Initial schema

Revision ID: 3667622c1768
Revises:
Create Date: 2026-08-05 13:06:17.239760

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3667622c1768"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
